modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/Cryptic-Mushroom/The-Midnight/issues"

[[mods]]
modId="midnight"
version="${file.jarVersion}"
displayName="The Midnight"
displayURL="https://minecraft.curseforge.com/projects/the-midnight"
updateJSONURL="https://gist.githubusercontent.com/gegy1000/a3f1f593c43f88d7f01a3560ac32e216/raw/midnight_updates.json"
logoFile="assets/midnight/logo.png"
credits=""
authors="cipherzerox, Endergized, Lachney, Gegy, Corail31, Martacus"
description='''
The Midnight adds a brand new dimension to explore full of unique adventures and dangers!
It's a dimension of perpetual darkness; the only light comes from crystals and the various flora and fauna of the dimension.
You may travel willingly to this dimension, though you may unwillingly be dragged by a Rifter into this strange, hostile world.
'''

[[dependencies.midnight]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
